[package]
name = "tether-agent"
version = "0.1.0"
authors = ["Stephen Buchanan <stephen.buchanan@random.studio>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["lib"]

[[example]]
name="publish"

[dependencies]
