version: "3.9"
services:
  nanomq:
    image: "emqx/nanomq:0.8.5"
    #environment:
    restart: "unless-stopped"
    # build: .
    ports:
    # remember HOST_PORT:CONTAINER_PORT
      - "15675:8083" # Websocket, match 15676 for the outside
      - "1883:1883" # Standard TCP for MQTT
