version: "3.9"
services:
  nanomq:
    image: "emqx/nanomq:0.8.5"
    #environment:
    restart: "unless-stopped"
    # build: .
    ports:
      - "5672:5672" # Standard TCP for AMQP
      - "8080:15672" # Standard Web Management
      - "1883:1883" # Standard TCP for MQTT
      - "15675:15675" # Standard MQTT-over-WebSocket
      #- "15676:15676" # TLS MQTT-over-WebSocket
