version: "3.9"
services:
  nanomq:
    image: "emqx/nanomq:0.10.1-slim"
    environment:
      - NANOMQ_WEBSOCKET_URL=nmq-ws://0.0.0.0:8083/ws
    restart: "unless-stopped"
    # build: .
    ports:
    # remember HOST_PORT:CONTAINER_PORT
      - "15675:8083" # Websocket, match 15676 for the outside
      - "1883:1883" # Standard TCP for MQTT
