[package]
name = "tether-rumqttc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = { version = "0.23.0", features = ["use-rustls", "websocket"] }
