name: "tether-broker"
services:
  mosquitto:
    image: "randomstudiotools/tether-broker"
    restart: "unless-stopped"
    ports:
      # remember HOST_PORT:CONTAINER_PORT
      - "15675:9001" # Websocket, match 15676 for the outside
      - "1883:1883" # Standard TCP for MQTT
