version: "3.9"
services:
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=tether
      - RABBITMQ_DEFAULT_PASS=sp_ceB0ss!
    restart: "unless-stopped"
    build: .
    ports:
      - "5672:5672" # Standard TCP for AMQP
      - "8080:15672" # Standard Web Management
      - "1883:1883" # Standard TCP for MQTT
      - "15675:15675" # Standard MQTT-over-WebSocket
      #- "15676:15676" # TLS MQTT-over-WebSocket
